[project]
name = "mtcs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.sources]
common = { workspace = true }

[project.scripts]
mcts = ""

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
